name: Feature request
description: Propose a new capability
labels: ["type:feature", "status:ready"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: One sentence user value
    validations:
      required: true
  - type: textarea
    id: user_story
    attributes:
      label: User story
      description: As a <role>, I want <capability> so that <benefit>.
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      value: |
        - [ ] …
        - [ ] …
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: [P1, P2, P3]
