name: Auto Version Bump

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version bump type (patch|minor|major)'
        required: true
        default: 'patch'
  push:
    branches:
      - develop  # only run on develop pushes

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: auto-version-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop         # ensure we operate on develop
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      # --- Perform the version bump locally ---
      - name: Bump version
        id: bump
        run: |
          TYPE="${{ github.event.inputs.bump || 'patch' }}"
          echo "Bumping version ($TYPE)..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm version "$TYPE" -m "chore(version): bump %s [skip ci]"
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      # --- Push changes to a temporary version-bump branch ---
      - name: Push version bump branch
        run: |
          BRANCH="version-bump/${{ github.run_id }}-${{ github.sha }}"
          git push origin HEAD:"$BRANCH"

      # --- Create the PR back into develop ---
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: develop
          branch: version-bump/${{ github.run_id }}-${{ github.sha }}
          title: "chore(version): bump to v${{ steps.bump.outputs.new_version }}"
          body: |
            Automated version bump to **v${{ steps.bump.outputs.new_version }}**
            - Triggered by: ${{ github.actor }}
            - Bump type: `${{ github.event.inputs.bump || 'patch' }}`
          commit-message: "chore(version): bump to v${{ steps.bump.outputs.new_version }} [skip ci]"
          labels: "auto,version-bump"
          delete-branch: true
