name: Auto Version Bump

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  pull_request:
    types: [closed]
    branches: [develop]   # run only when PRs into develop are closed

jobs:
  create-version-bump:
    # run only if the PR was merged AND it wasn't a version-bump PR (avoid recursion)
    if: >
      github.event.pull_request.merged == true &&
      !startsWith(github.event.pull_request.head.ref, 'version-bump/')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # Determine bump type from PR labels: major/minor/patch (default)
      - name: Determine version bump type
        id: bump-type
        run: |
          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'major') }}" == "true" ]]; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif [[ "${{ contains(github.event.pull_request.labels.*.name, 'minor') }}" == "true" ]]; then
            echo "type=minor" >> $GITHUB_OUTPUT
          else
            echo "type=patch" >> $GITHUB_OUTPUT
          fi

      # Bump version in package.json WITHOUT creating a tag (semantic-release will tag later)
      - name: Update version
        id: bump-version
        run: |
          npm --no-git-tag-version version ${{ steps.bump-type.outputs.type }}
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      # Create a PR from a new branch back into develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: version-bump/${{ github.run_id }}-${{ github.sha }}
          title: "chore(version): bump to v${{ steps.bump-version.outputs.version }}"
          commit-message: "chore(version): bump to v${{ steps.bump-version.outputs.version }} [skip ci]"
          body: |
            🤖 Automatic version bump triggered by merge of #${{ github.event.pull_request.number }}

            **Changes**
            - Version: `v${{ steps.bump-version.outputs.version }}`
            - Type: `${{ steps.bump-type.outputs.type }}`

            This PR was automatically created by the Auto Version Bump workflow.
          labels: |
            automated
            version-bump
          delete-branch: true

      # Optional: comment back on the original PR for traceability
      - name: Comment on original PR
        uses: actions/github-script@v7
        with:
          script: |
            const newVersion = '${{ steps.bump-version.outputs.version }}'
            const bumpType = '${{ steps.bump-type.outputs.type }}'
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `📦 Created version bump PR to **v${newVersion}** (${bumpType}).`
            })
