name: Release

on:
  push:
    branches: [ develop ]

permissions:
  contents: write   # needed for tags, releases, pushing refs

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # full history for semantic-release & tags

      - name: Ensure tags are present
        run: git fetch --tags --force

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present

      # Invoke semantic-release without mutating package-lock.json
      - name: Semantic Release
        id: sr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx -y semantic-release

      # Create or update maintenance branch for this minor line
      - name: Create/Update maintenance branch for this line
        run: |
          TAG=$(git describe --tags --abbrev=0)
          V=${TAG#v}
          MAJOR=$(echo "$V" | cut -d. -f1)
          MINOR=$(echo "$V" | cut -d. -f2)
          LINE="releases/v${MAJOR}.${MINOR}"
          echo "Maint line: $LINE from tag $TAG"
          # create or move branch to the tag (local), then push
          if git show-ref --verify --quiet "refs/heads/$LINE"; then
            git branch -f "$LINE" "$TAG"
          else
            git branch "$LINE" "$TAG"
          fi
          git push -u origin "$LINE" --force-with-lease

      # Optional: keep main pointing at the released tag (FF via ref update)
      - name: Create PR to update main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: sync/develop-to-main
          title: "chore(release): sync develop to main"
          body: |
            Automated PR to bring latest release from develop into main.
            - Triggered by tag: ${{ steps.sr.outputs.new_release_version || 'manual release' }}
            - Source: ${{ github.ref_name }}
          labels: release
          delete-branch: true
